version: '3.4'

services:
  db:
    container_name: splitly-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: splitly_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks: [ sp-net ]

  core:
    container_name: splitly-core
    build: .
    networks: [ sp-net ]
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/splitly_app
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - db

networks:
  sp-net:
    name: splitly-network
    driver: bridge