version: '3.4'

services:
  postgreesql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
      - POSTGRES_USER=admin
      - POSTGRES_DB=splitly_db
      - DDL_PASSWORD=${DB_DDL_PASSWORD}
      - DML_PASSWORD=${DB_DML_PASSWORD}
    volumes:
          - ./src/main/resources/init/postgres/01_init_postgres.sh:/docker-entrypoint-initdb.d/01_init_postgres.sh