spring:
  liquibase:
    change-log: "classpath*:db/changelog/db.changelog-master.yaml"
    url: ${DB_URL}
    user: ${DB_DDL_USERNAME}
    password: ${DB_DDL_PASSWORD}
    default-schema: splitly_app
  datasource:
      url: ${DB_URL}
      username: ${DB_DML_USERNAME}
      password: ${DB_DML_PASSWORD}
      driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
application:
  hello-world: ${HELLO_WORLD}
