spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
application:
  hello-world: ${HELLO_WORLD:Hello World}
